services:
  postgres:
    image: postgres:18
    container_name: plavdata_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      TZ: "${TIMEZONE}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale-provider=icu --icu-locale=cs-CZ"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - db-network

  backend:
    build:
      context: ./backend
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: plavdata_be
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - proxy-net
      - db-network
    expose:
      - "8000"
    volumes:
      - "./backend/data:/app/data"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENV=production
      - CORS_ORIGINS=${CORS_ORIGINS:-}
      - TARGET_CLUB=${TARGET_CLUB}
      - SECRET_KEY=${SECRET_KEY}
      - LOKI_ENABLED=${LOKI_ENABLED:-false}
      - LOKI_URL=${LOKI_URL:-}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: plavdata_fe
    networks:
      - proxy-net
    restart: unless-stopped

volumes:
  pgdata:
    

networks:
  db-network:
    driver: bridge
  proxy-net:
    external: true
    name: ${PROXY_NETWORK}
