services:
  backend:
    build: ./backend
    container_name: plavdata_be
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: docker.io/library/postgres:16
    container_name: plavdata_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # init-db:
  #   build: ./backend
  #   container_name: init_db_runner
  #   working_dir: /app
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: plavdata
  #   command: ["python", "-m", "scripts.db.init_db"]
  #   restart: "no"   # run once and stop
  #
  # sync-pb:
  #   build: ./backend
  #   container_name: sync_pb_runner
  #   working_dir: /app
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: plavdata
  #   command: ["python", "-m", "scripts.db.sync_personal_bests"]
  #   restart: "no"   # run once and stop

volumes:
  pgdata:
